config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'homes#index'
  get 'home/about' => 'homes#about'

  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
    resources :favorites, only: [:index]
  end
  root 'homes#index'

end

app/models/favorite.rb
class Favorite < ActiveRecord::Base # :nodoc:
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: { scope: :post_id }
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController # :nodoc:
  before_action :authenticate_user!
  # before_action :authorize_create, only: :create
  # before_action :authorize_destroy, only: :destroy

  # Favorite
  def create
    favorite          = Favorite.new
    favorite.user     = current_user
    favorite.post     = post

    respond_to do |format|
      if favorite.save
        @user_fav ||= post.fav_for(current_user)
        format.html { redirect_to post, notice: 'FAVORITED!' }
        format.js { render }
      else
        format.html { redirect_to post, alert:  'Already favorited' }
        format.js { render js: "alert('Can\ 't favorite, please refresh');" }
      end
    end
  end

  def destroy
    # Unfavorite
    favorite.destroy
    @user_fav = post.fav_for(current_user)
    respond_to do |format|
      format.html { redirect_to post_path(favorite.post_id), notice: 'Un-favorited' }
      format.js { render }
    end
  end

  private

  # def authorize_create
  # end
  #
  # def authorize_destroy
  # end

  def post
    @post ||= Post.friendly.find params[:post_id]
  end

  def favorite
    @favorite ||= Favorite.find params[:id]
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/views/favorites/_favorite.html.erb
<% if user_fav %>
  <%= link_to "Un-Favorite", post_favorite_path(@post, user_fav), method: :delete, remote: true %>
<% else %>
  <%= link_to "Favorite", post_favorites_path(@post), method: :post, remote: true %>
<% end %>

<!-- user_fav here is not a local variable -->

app/views/favorites/create.js.erb
$("#post-fav").html("<%= j render 'favorite', user_fav: @user_fav %>");

app/views/favorites/destroy.js.erb
$("#post-fav").html("<%= j render 'favorite', user_fav: @user_fav %>");