config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'homes#index'
  get 'home/about' => 'homes#about'

  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
    resources :favorites, only: [:index]
  end
  root 'homes#index'

end

app/models/comment.rb
class Comment < ActiveRecord::Base # :nodoc:
  validates :body, presence: true

  belongs_to :post
  belongs_to :user
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController # :nodoc:
  before_action :find_post
  # before_action :comment_params, only: :update
  def create
    @comment      = Comment.new comment_params
    @comment.post = @post
    # Why is my comment nil? --> SOLVED, needed @comment = Comment.new in SHOW
    # method of POSTS controller

    # Mailer feature
    # CommentsMailer.notify_post_owner(@comment).deliver_later

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), notice: 'Comment created' }
        format.js   { render :create_success }
        # byebug
      else
        format.html { render '/posts/show'   }
        format.js   { render :create_failure }
      end
    end
  end

  def edit
    @comment = Comment.find params[:id]
  end

  def update
    @comment = Comment.find params[:id]
    comment_params = params.require(:comment).permit(:body)
    respond_to do |format|
      if @comment.update comment_params
        format.html { redirect_to post_path(@post), notice: 'Comment Updated' }
        format.js { render :update_success }
      else
        flash[:alert] = 'Edit failed'
        format.html { render '/questions/show' }
        format.js { render :update_failure }
      end
    end
  end

  def destroy
    @comment = Comment.find params[:id]
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@comment.post), notice:   'Deleted.' }
      format.js { render }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_post
    @post = Post.friendly.find params[:post_id]
  end
end

app/helpers/comments_helper.rb
module CommentsHelper # :nodoc:
  # Helper method to help hide the comment when prepended
  def element_hide(flag)
    flag ? 'display:none;' : ''
  end
end

app/views/comments/_comment.html.erb
<!-- Here we use a helper method to help hide the style -->
<% hidden_flag ||= false %>

<div id="<%= dom_id(comment) %>", style="<%= element_hide(hidden_flag)%>">
  <%= comment.body %>
  <br />
  <%= link_to "Edit", edit_post_comment_path(@post, comment), remote: true, data: { toggle: "modal", target: "#edit-comment" } %>
  |
  <%= link_to "Delete Comment", post_comment_path(@post, comment), data: {confirm: "Are you sure?"}, method: :delete, remote: true %>
  <hr />
</div>

app/views/comments/_form.html.erb
<%= comment.errors.full_messages.join(", ") %>
<%= form_for [@post, comment], remote: true do |c| %>
  <div class='form-group'>
    <%= c.text_area :body, :class => "form-control", :rows => "5" %>
    <br /> <br />
    <%= c.submit "Submit Comment", class: "btn btn-default btn-md" %>
  </div>
<% end %>

app/views/comments/_modal_form.html.erb
<%= @comment.errors.full_messages.join(", ") %>
<%#= form_for @comment, url: post_comments_path(@post) do |f| %>
<%# adding a remote: true option to the form makes it so that the form submits
    with AJAX (prevent the default as well) %>
<%= form_for [@post, @comment], remote: true do |f|  %>
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Comment</h4>
      </div>
      <div class="modal-body">
        <%= f.text_area :body %>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
        <%= f.submit data: {disable_with: "submitting..."}, class: "btn btn-primary" %></button>
      </div>
    </div>
  </div>
<% end %>

app/views/comments/create_failure.js.erb
$("#comment-form").html("<%= j render '/comments/form', comment: @comment %>");

app/views/comments/create_success.js.erb
// We can pass any additional arguments when we use j render
// Here we pass a hidden_flag: true

var comment_html = "<%= j render '/comments/comment', comment: @comment, hidden_flag: true %>";

// Then we slide down afterwards
$("#comments").prepend(comment_html);
$("#<%= dom_id(@comment) %>").slideDown(1000);

$("#comment-form").html("<%= j render '/comments/form', comment: Comment.new %>")

app/views/comments/destroy.js.erb
$("#<%= dom_id(@comment) %>").fadeOut(1000, function(){
  $(this).remove();
});

app/views/comments/edit.js.erb
$("#edit-comment").html("<%= j render 'modal_form' %>");

app/views/comments/update_failure.js.erb
$("#comment-form").html("<%= j render '/comments/form', comment: @comment %>");

app/views/comments/update_success.js.erb
$("#<%= dom_id(@comment) %>").html("<%= j render '/comments/comment', comment: @comment %>");
$("#edit-comment").modal('hide')