config/routes.rb
Rails.application.routes.draw do

  get 'home' => 'homes#index'
  get 'home/about' => 'homes#about'

  resources :posts do
    resources :comments, only: [:create, :destroy, :edit, :update]
    resources :favorites, only: [:create, :destroy]
  end

  resources :users, only: [:new, :create, :show, :edit, :update]

  resources :sessions, only: [:new, :create] do
    delete :destroy, on: :collection
    resources :favorites, only: [:index]
  end
  root 'homes#index'

end

app/models/category.rb
class Category < ActiveRecord::Base # :nodoc:
  validates :title, presence: true
  has_many :posts
end

app/models/comment.rb
class Comment < ActiveRecord::Base # :nodoc:
  validates :body, presence: true

  belongs_to :post
  belongs_to :user
end

app/models/contact.rb
class Contact < ActiveRecord::Base
  validates :email, presence: true 
end

app/models/favorite.rb
class Favorite < ActiveRecord::Base # :nodoc:
  belongs_to :post
  belongs_to :user

  validates :user_id, uniqueness: { scope: :post_id }
end

app/models/post.rb
class Post < ActiveRecord::Base # :nodoc:
  extend FriendlyId
  friendly_id :title, use: :history

  validates :title, presence: true,
                    uniqueness: true,
                    length: { minimum: 7 }

  validates :body, length: { minimum: 5 }, presence: true

  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :taggings, dependent: :destroy
  has_many :tags, through: :taggings

  belongs_to :user
  belongs_to :category

  def self.search(search)
    if search
      where(['title ILIKE ? OR body ILIKE ?', "%#{search}%", "%#{search}%"])
    else
      all
    end
  end

  def body_snippet
    if body.length > 100
      body[0..99] + '...'
    else
      body
    end
  end

  def fav_for(user)
    favorites.find_by_user_id user if user
  end
end

app/models/tag.rb
class Tag < ActiveRecord::Base # :nodoc:
  has_many :taggings, dependent: :destroy
  has_many :posts, through: :taggings

  validates :name, presence: true, uniqueness: :true
end

app/models/tagging.rb
class Tagging < ActiveRecord::Base # :nodoc:
  belongs_to :tag
  belongs_to :post

  validates :tag_id, uniqueness: { scope: :post_id }
end

app/models/user.rb
class User < ActiveRecord::Base # :nodoc:
  has_secure_password
  validates :email, presence: true,
                    uniqueness: true,
                    format:  /\A([\w+\-].?)+@[a-z\d\-]+(\.[a-z]+)*\.[a-z]+\z/i

  has_many :posts, dependent: :destroy
  has_many :comments, dependent: :destroy
  has_many :favorites, dependent: :destroy
  has_many :favorited_posts, through: :favorites, source: :post

  def full_name
    "#{first_name} #{last_name}".titleize
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController # :nodoc:
  before_action :find_post
  # before_action :comment_params, only: :update
  def create
    @comment      = Comment.new comment_params
    @comment.post = @post
    # Why is my comment nil? --> SOLVED, needed @comment = Comment.new in SHOW
    # method of POSTS controller

    # Mailer feature
    # CommentsMailer.notify_post_owner(@comment).deliver_later

    respond_to do |format|
      if @comment.save
        format.html { redirect_to post_path(@post), notice: 'Comment created' }
        format.js   { render :create_success }
        # byebug
      else
        format.html { render '/posts/show'   }
        format.js   { render :create_failure }
      end
    end
  end

  def edit
    @comment = Comment.find params[:id]
  end

  def update
    @comment = Comment.find params[:id]
    comment_params = params.require(:comment).permit(:body)
    respond_to do |format|
      if @comment.update comment_params
        format.html { redirect_to post_path(@post), notice: 'Comment Updated' }
        format.js { render :update_success }
      else
        flash[:alert] = 'Edit failed'
        format.html { render '/questions/show' }
        format.js { render :update_failure }
      end
    end
  end

  def destroy
    @comment = Comment.find params[:id]
    @comment.destroy
    respond_to do |format|
      format.html { redirect_to post_path(@comment.post), notice:   'Deleted.' }
      format.js { render }
    end
  end

  private

  def comment_params
    params.require(:comment).permit(:body)
  end

  def find_post
    @post = Post.friendly.find params[:post_id]
  end
end

app/controllers/homes_controller.rb
class HomesController < ApplicationController

  def about
  end

  def index
  end

end

app/controllers/posts_controller.rb
class PostsController < ApplicationController # :nodoc:
  before_action :authenticate_user!, except: [:index, :show]
  before_action :find_post, only: [:show, :edit, :update, :destroy]

  def new
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)

    if @post.save
      redirect_to post_path(@post), notice: 'Post created!'
    else
      flash[:alert] =
        'Failed to post. Please make sure your post has a title and a body'
      render :new
    end
  end

  def show
    @comment = Comment.new
  end

  def index
    # Sort by order and pagination with kaminari gem
    # @posts = Post.all
    @posts = Post.order('id DESC').page(params[:page]).per(10)
    if params[:term].present?
      @posts = Post.search(params[:term]).page(params[:page]).per(10)
    end
  end

  def edit
  end

  def update
    if @post.update post_params
      redirect_to @post, notice: 'Post has been updated'
    else
      render :edit
    end
  end

  def destroy
    @post.destroy
    redirect_to posts_path, notice: 'Post deleted.'
  end

  private

  def post_params
    params.require(:post).permit(:title, :body, tag_ids: [])
  end

  def find_post
    @post = Post.friendly.find params[:id]
  end

  def user_fav
    @user_fav ||= @post.fav_for(current_user)
  end
  helper_method :user_fav
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController # :nodoc:
  def new
  end

  def create
    @user = User.find_by_email params[:email]
    if @user && @user.authenticate(params[:password])
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Logged in'
    else
      flash[:alert] = 'Wrong email or password'
      render :new
    end
  end

  def destroy
    session[:user_id] = nil
    redirect_to root_path, notice: 'Logged out!'
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController # :nodoc:
  def new
    @user = User.new
  end

  def create
    @user = User.new user_params
    if @user.save
      session[:user_id] = @user.id
      redirect_to root_path, notice: 'Logged in!'
    else
      render :new
    end
  end

  def edit
    @user = User.find(current_user)
  end

  def update
    @user = User.find(current_user)
    if new_password && @user.update(user_params)
      redirect_to posts_path, notice: 'Account information updated!'
    else
      render :edit
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name,
                                 :last_name,
                                 :email,
                                 :password,
                                 :password_confirmation)
  end

  def new_password
    (params[:old_password] != params['user']['password']) && (params['user']['password'] == params['user']['password_confirmation'])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper # :nodoc:
  # Helper method to help hide the comment when prepended
  def element_hide(flag)
    flag ? 'display:none;' : ''
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Blog</title>
  <%= stylesheet_link_tag "bootstrap.min.css"  %>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>


<nav class="navbar navbar-default">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to "Blog", home_path, class: "navbar-brand" %>
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to "About Page", home_about_path, method: :get %></li>
        <li><%= link_to "Blog Posts", posts_path %></li>
        <li><%= link_to "New Blog Post", new_post_path %></li>
      </ul>
      <ul class="nav navbar-nav navbar-right">
        <% if user_signed_in? %>
          <li> <%= link_to "#{current_user.full_name}" %> </li>
          <li> <%= link_to "Favorited Posts", user_path(current_user) %> </li>
          <li> <%= link_to "Logout", sessions_path, method: :delete,
          data: {confirm: "are you sure you want to log out?"}%> </li>
        <% else %>
          <li> <%= link_to "Login", new_session_path %> </li>
          <li> <%= link_to "Sign Up", new_user_path %>  </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>


<div class="container">
  <%= yield %>
</div>
<hr />
<nav class="navbar navbar-inverse navbar-fixed-bottom">
  <div class="container-fluid">
    <span>&#169; 2016</span>
    <p style="float: right">Built and maintained by Jonathan Wong </a></p>
  </div>
</nav>
</body>
</html>